### ISSUE TITLE
mec won´t start?!

### ISSUE THREAD

**Issue by mmuncan** [jm33-m0/mec#38] opened 2020-01-18 12:34 UTC
kali gives me this:
```
root@localhost:~/h4ck/massExpConsole# python3 mec.py 
Traceback (most recent call last):
  File "mec.py", line 10, in <module>
    main.run()
  File "/root/h4ck/massExpConsole/lib/cli/main.py", line 418, in run
    print(console.INTRO)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 11-14: ordinal not in range(128)
```

**Comment by jm33-m0** [comment] 2020-01-19 02:13
1. You need to run `install.py` first: [see wiki](https://github.com/jm33-m0/mec/wiki/How-to-Install#run-installer)
2. ` UnicodeEncodeError: 'ascii' codec can't encode characters in position 11-14: ordinal not in range(128)`, looks like your `python3` is trying to use `ascii` codec? However [by default](https://docs.python.org/3/howto/unicode.html#python-s-unicode-support) python3 uses utf-8 codec. I think you should check your config.

**Comment by mmuncan** [comment] 2020-01-19 03:07
root@localhost:~/h4ck/massExpConsole# python3 install.py 
Traceback (most recent call last):
  File "install.py", line 27, in <module>
    import distro
ImportError: No module named 'distro'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "install.py", line 28, in <module>
    except ModuleNotFoundError:
NameError: name 'ModuleNotFoundError' is not defined
root@localhost:~/h4ck/massExpConsole#

**Comment by jm33-m0** [comment] 2020-01-19 04:20
Are you using the latest version from Github? BTW are you sure you are using python**3**? What's the version of your python?

Since this cannot be reproduced by me, I am closing this issue

**Closed by jm33-m0** 2020-01-19 04:20 UTC

**Comment by mmuncan** [comment] 2020-01-19 04:39
as oyu can see from the copy paste i am using python3. it is strange coz at home on my kali i could easily install it?!

**Comment by jm33-m0** [comment] 2020-01-19 04:40
# Have you read the wiki?

- [ ] Yes, and I did exactly what it says

`https://github.com/jm33-m0/mec/wiki`

# Environment

## Python version

Just type `python3` and check its version

```
# Put your result here

```

## Your system

```
cat /etc/*release*
# Put your result here

```

**Comment by jm33-m0** [comment] 2020-01-19 04:42
I have just created an issue template, you can try to trouble-shoot yourself

**Comment by jm33-m0** [comment] 2020-01-19 04:44
> as oyu can see from the copy paste i am using python3

Make sure you have read this: https://github.com/jm33-m0/mec/wiki/How-to-Install#dependencies
